version: "3.7"

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
      cache_from:
        - "${WEB_IMAGE}"
    image: "${WEB_IMAGE}"
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py makemigrations &&
              python manage.py runserver 0.0.0.0:8000"
    volumes:
      - static_volume:"/usr/src/app/staticfiles"
      - media_volume:"/usr/src/app/mediafiles"
    expose:
      - 8000
    env_file: .env
    
volumes:
  static_volume:
  media_volume: