# Generated by Django 2.2.17 on 2020-12-18 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_leadcomplete'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadcomplete',
            name='client',
            field=models.ManyToManyField(to='core.Client'),
        ),
    ]
