# Generated by Django 2.2.17 on 2020-12-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_leadcomplete_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadcomplete',
            name='firstname',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
