# Generated by Django 2.2.17 on 2020-12-21 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_leadcomplete_firstname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='user',
        ),
        migrations.AddField(
            model_name='lead',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Client'),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.LeadComplete'),
        ),
        migrations.AddField(
            model_name='leadcomplete',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leadcomplete',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leadcomplete',
            name='lastname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leadcomplete',
            name='linkedinLead',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leadcomplete',
            name='notes',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='leadcomplete',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leadcomplete',
            name='salesloftId',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='leadcomplete',
            name='state',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leadcomplete',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leadcomplete',
            name='zipCode',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('touches', models.IntegerField()),
                ('opens', models.IntegerField()),
                ('click', models.IntegerField()),
                ('visits', models.IntegerField()),
                ('pageviews', models.IntegerField()),
                ('leadComplete', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.LeadComplete')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('owlerLink', models.CharField(max_length=255)),
                ('craftUrl', models.CharField(max_length=255)),
                ('companyLinkedin', models.CharField(max_length=255)),
                ('leadComplete', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.LeadComplete')),
            ],
        ),
        migrations.CreateModel(
            name='ClientLeadScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('clientAcceptane', models.BooleanField(default=False)),
                ('client', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Client')),
                ('leadComplete', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.LeadComplete')),
            ],
        ),
        migrations.AddField(
            model_name='leadcomplete',
            name='company',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.CompanyLead'),
        ),
        migrations.AddField(
            model_name='leadcomplete',
            name='engagment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Engagement'),
        ),
    ]
