# Generated by Django 2.2.17 on 2020-12-21 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201221_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadcomplete',
            name='company',
        ),
        migrations.RemoveField(
            model_name='leadcomplete',
            name='engagment',
        ),
    ]
