# Generated by Django 2.2.17 on 2020-12-21 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201221_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientleadscore',
            old_name='clientAcceptane',
            new_name='clientAccepted',
        ),
    ]
