# Generated by Django 2.2.17 on 2020-12-28 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_user_is_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companylead',
            name='leadComplete',
        ),
        migrations.AddField(
            model_name='companylead',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companylead',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leadcomplete',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.CompanyLead'),
        ),
    ]
