# Generated by Django 2.2.17 on 2020-12-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20201228_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='active',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
