# Generated by Django 2.2.17 on 2020-12-30 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='salesloftkey',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
