# Generated by Django 2.2.17 on 2020-12-30 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_client_salesloftkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadcomplete',
            name='client',
        ),
        migrations.AddField(
            model_name='leadcomplete',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Client'),
        ),
    ]
