# Generated by Django 2.2.17 on 2020-12-30 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20201230_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='replied',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
