# Generated by Django 2.2.17 on 2020-12-30 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_engagement_replied'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('personId', models.IntegerField()),
                ('leadComplete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.LeadComplete')),
            ],
        ),
    ]
