# Generated by Django 2.2.17 on 2020-12-30 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20201230_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='companylead',
            name='alexaRank',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companylead',
            name='employeeBand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companylead',
            name='estimatedAge',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companylead',
            name='keywords',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='companylead',
            name='revenueBand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
