# Generated by Django 2.2.17 on 2020-12-31 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20201230_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companylead',
            old_name='alexaRank',
            new_name='city',
        ),
        migrations.AddField(
            model_name='companylead',
            name='companyFacebook',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companylead',
            name='companyIndustry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companylead',
            name='similarCompanyOne',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companylead',
            name='similarCompanyThree',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companylead',
            name='similarCompanyTwo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companylead',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
