# Generated by Django 2.2.17 on 2020-12-31 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20201231_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='companylead',
            name='alexaRank',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
