# Generated by Django 2.2.17 on 2020-12-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_newsarticles'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='descriptionEncoded',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='message',
            name='subjectEncoded',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
