# Generated by Django 2.2.17 on 2020-12-31 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20201231_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='descriptionEncoded',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
