# Generated by Django 2.2.17 on 2021-01-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_leadcomplete_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadcomplete',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('favorite', 'Favorite'), ('archived', 'Archived'), ('acccepted', 'Accepted')], default='open', max_length=32),
        ),
    ]
